name: Fast Instagram Bot

on:
  workflow_dispatch:
    inputs:
      recipient:
        description: 'Instagram username to send reels to'
        required: true
        default: 'poorviiiiiiie'
      count:
        description: 'Number of reels to send'
        required: true
        default: '3'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install selenium

      - name: Configure Chromium
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

      - name: Run the bot
        env:
          IG_SESSIONID: ${{ secrets.IG_SESSIONID }}
        run: |
          python Insta_Bot/bot.py "${{ github.event.inputs.recipient }}" "${{ github.event.inputs.count }}"
